spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/miniapp?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: root


mybatis:
  mapper-locations: classpath:Mapper/*.xml
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: false # 数据库下划线自动转驼峰标示关闭
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
